name: Gatsby Publish

on:
  push:
    branches:
      - main
      - mattbowen-usds/v3-48-gatsby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          working-dir: tech-far-hub
